### ISSUE TITLE
eagle2 + minimac4 for phasing and imputation? 

### ISSUE THREAD

**Issue by Shicheng-Guo** [ikmb/eagleimp#2]
I am wondering is this tool equal to eagle2 + minimac4 for phasing and imputation? Thanks.

**Comment by lwienbrandt** [comment]
Hi Shicheng-Guo,
thanks for pointing this out.
Our tool EagleImp behaves similar to Eagle2+Minimac as it performs phasing and imputation as well. However, while the phasing step is based on the same algorithm Eagle2 (Loh et al., 2016) uses, the imputation step is based on the PBWT algorithm (Durbin, 2014) which is different to Minimac and thus may deliver slightly different results. Please have a look at our preprint available at https://biorxiv.org/cgi/content/short/2022.01.11.475810v1 to find out about our improvements compared to the original tools.
I hope, this satisfies your question?
Best, Lars
