### ISSUE TITLE
Multi-species

### ISSUE THREAD

**Issue by adamtaiti** [ikmb/eagleimp#4]
Hi Lars! That is such a nice work.
This is not an issue but a kind request. I would like to make use of eagleimp in bovine and one of the restrictions is the chromosome numbering (1-22, X and Y). Is it possible to implement a way to generalize the code for especies with larger number of chromosomes or to take into account autosomes vs sexual/MT that would allow users to use it in different species?

Thank you in advance!

**Comment by lwienbrandt** [comment]
Hi Adam. Thanks for your suggestion, and it's indeed a good one. I will have a look into it and keep you updated. The only issue is time (as always... ;-)).

**Comment by lwienbrandt** [comment]
Hey, I've finally managed to spend some time for this issue. I hope that it is solved by now. So, there is no chromosome number limitation anymore and also it can be arbitrarily named. However, the launch script still focuses on human chromosomes, i.e. it handles 23/X with special treatment.
Have fun!
