### ISSUE TITLE
Target and reference build compatibility

### ISSUE THREAD

**Issue by h171e** [ikmb/eagleimp#5]
@marchoeppner @ghemmrich @lwienbrandt @eikematthias 
My vcf is in hg38, could execute with qref from eagleimp website which is in hg19 but wonder if there is a qref in hg38 because I don't know if the process was done correctly and I don't know how to convert my target vcf to hg19 and then back to hg38. I could not use the program with a different reference in hg38 either in vcf.gz format or converted to qref. 

The message I got from the phasing and imputation made with the downloaded qref includes warnings like this one "WARNING: More than 50% of the target variants not found in reference! Wrong genome built?". 

The purpose of trying to do phasing and imputation on my vcf file is to try to make it compatible with a pgsc_calc polygenic score calculator since matching rates are low with my current vcf file suggesting missing variants. 

I was told I needed a phased and imputed gvcf file in order to get high matching rates. This target is not a gvcf thou and I am not sure if its going to get better results, but I don't know how to generate a phased and imputed gvcf file, all I have is my target BAM file that I think is needed for this. So if somebody can also help with this I would appreciate it very much. Here is the terminal output message from the command. Thank you.

**eagleimp --geneticMap /genetic_map_hg19_chr1.txt --ref /1.genotypes.qref --target /chr1.vcf.gz --allowRefAltSwap -o /PhasedEagleimp/chr1**

----------------------------------------------------------------
--- Chunk 1/2:
----------------------------------------------------------------
Reading data: 0%...1%...3%...6%...8%...10%...12%...14%...17%...19%...21%...23%...25%...28%...30%...32%...34%...36%...39%...41%...43%...45%...47%...50%...52%...54%...56%...58%...61%...63%...65%...67%...69%...72%...74%...76%...78%...80%...82%...85%...87%...89%...91%...93%...96%...98%..100% (chunk end)

1010 variants in both target and reference are used for phasing.
  (Of these are 2 variants in the overlap to next chunk.)
3441440 variants exclusively in reference will be imputed.
  (Of these are 3043 variants in the overlap to next chunk.)
Imputation output will contain 3442450 variants.
  (3045 in the overlap to next chunk.)

Physical distance range:        119261014 base pairs
Genetic distance range:         150.901703 cM
Average #SNPs per cM in target: 7

  REF/ALT were swapped in 477 variants.
  Dropped 180786 variants not found in reference.
WARNING: More than 50% of the target variants not found in reference! Wrong genome built?
  Dropped 4513 variants with allele mismatches.
  3441440 variants in reference but not in target.
  No multi-allelic reference-only variants.

Av. missing rate in target genotypes: 0.001980

Phasing:
Using 4 threads for phasing.
Phasing iteration 1/1 (K=5008): 0%.100%

Imputation:
Using 4 threads for calculating set-maximal matches.
Using 3 threads and 1 temporary files for imputation.
Imputing: 0%.100%
Concatenating temporary files...

----------------------------------------------------------------
--- Chunk 2/2:
----------------------------------------------------------------
Reading data: 0%...1%...3%...6%...8%...10%...12%...14%...17%...19%...21%...23%...25%...28%...30%...32%...34%...36%...39%...41%...43%...45%...47%...50%...52%...54%...56%...58%...61%...63%...65%...67%...69%...72%...74%...76%...78%...80%...83%...85%...87%...89%...91%...94%...96%...98%..100%
974 variants in both target and reference are used for phasing.
3060155 variants exclusively in reference will be imputed.
Imputation output will contain 3061129 variants.

Physical distance range:        129335362 base pairs
Genetic distance range:         142.149445 cM
Average #SNPs per cM in target: 7

  REF/ALT were swapped in 481 variants.
  Dropped 180936 variants not found in reference.
WARNING: More than 50% of the target variants not found in reference! Wrong genome built?
  Dropped 4274 variants with allele mismatches.

  3060155 variants in reference but not in target.
  No multi-allelic reference-only variants.

Av. missing rate in target genotypes: 0.001027

Phasing:
Using 4 threads for phasing.
Phasing iteration 1/1 (K=5008): 0%.100%

Imputation:
Using 4 threads for calculating set-maximal matches.
Using 3 threads and 1 temporary files for imputation.
Imputing: 0%.100%
Concatenating temporary files...
Combining chunk files...

----------------------------------------------------------------
--- Summary:
----------------------------------------------------------------
1982 variants in both target and reference were used for phasing.
6498552 variants exclusively in reference were imputed.
Imputation output contains 6500534 variants.

Physical distance range:        248596325 base pairs
Genetic distance range:         293.051147 cM
Average #SNPs per cM in target: 7

  REF/ALT were swapped in 958 variants.
  Dropped 361722 variants not found in reference.
  Dropped 8787 variants with allele mismatches.

  6498552 variants in reference but not in target.
  No multi-allelic reference-only variants.

Av. missing rate in target genotypes: 0.001514
Imputation conflict rate (relation of haplotypes with no overlap and dosage set to allele frequency to total haplotypes): 0.001602

TIMER              ELAPSED CPUTIME SYSTIME  IOREAD IOWRITE  MINFLT  MAJFLT   VCONT INVCONT
**TOTAL**          271.840  81.668  45.272 1311424       0  902774   47571  978385   11072
├Read data         215.898  12.112  28.059  167032       0  563896    9208  460247      46
├Phasing             0.499   0.445   0.011    2016       0     963      15      20       7
│└iter 1             0.498   0.444   0.011    2016       0     963      15      20       7
└Imputation+Write   43.683  65.160  16.402 1028472       0  301077   36539  499310   11008
 ├refPBWT            0.115   0.028   0.086       0       0    5155       0       0       0
 ├findSetMax         0.452   0.193   0.012     176       0      22       1       6       1
 └imputeBunch        2.842   5.490   0.000    2728       0     297      50      58      10

**Comment by lwienbrandt** [comment]
Dear @hectorfp3000,
as you used EagleImp with a hg19 reference on a hg38 target, your output was very expected. The output VCF file will also be useless, as you mixed both genome builds now. So, either convert your target to hg19 (using the UCSC liftover tool) or use a hg38 reference.
I would also recommend that you use a larger reference panel than 1000 Genomes. So, simply use our webservice at hybridcomputing.ikmb.uni-kiel.de ;-)
Regarding the pgsc calculation, I have no experience with GVCF. Simply try with a properly imputed VCF file first.
But before I close this issue, I'm rather interested in your sentence "I could not use the program with a different reference in hg38 either in vcf.gz format or converted to qref.". So, why's that? Can you give an example and post the output here?
Best, Lars

**Comment by h171e** [comment]
I was able to execute the program with the references, just needed to adjust the amount of ram used with the `--maxChunkMemory` argument. Matching rates for the polygenic scores were up from 30% to 86%. Could matching rates be higher or results more accurate by merging biallelic positions in the imputed vcf output? These positions where originally multi-allelic positions that were split before for imputation input.

The vcfs used where sorted, left aligned, trimmed, and split using gatk and bcftools, but bcftools was not able to unsplit or merge back the biallelic sites in the imputed vcf that where multi-allelic in the original vcf and don’t know the reason or how to fix it. I read that splited multi-allelics should be merged back in order to get better polygenic scores, so I wonder if achieving this step could improve matching rates or the overall calculation accuracy.

The input files for imputation where preprocessed with bcftools and gatk for sorting, left align, trimming, and splitting. Two sets where tried, one sorted, split, and normalized with bcftools and the other set with gatk but outcomes where the same in terms of calculator error message and attempt to merge back the multi-allelic sites and trying to obtain stats with bcftools.

Bcftools:
1.	bcftools sort **input.vcf** -o **output.vcf**
2.	bcftools norm -m+any **input.vcf** -o **output.vcf**
3.	bcftools norm -d any **input.vcf** -f **reference-fasta.fna** -o **output.vcf**

Gatk:
1.	bcftools sort **input.vcf** -o **output.vcf**
2.	gatk LeftAlignAndTrimVariants -R **reference.fasta** -V **input.vcf** -O **output.vcf** --max-indel-length 800 --split-multi-allelics

The following error messages were obtained from the attempt to merge back the biallelic sites for the vcf that was first left aligned, normalized, and split using bcftools and then imputed using an eagleimp local install.

**bcftools norm -m+both and -m+any** 
The REF prefixes differ: C vs A (1,1)
Failed to merge alleles at chr1:1715541

**bcftools norm -m+both -f GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna** 
Reference allele mismatch at chr1:357101 .. REF_SEQ:'G' vs VCF:'C'	

The program was able to execute phasing, imputation, and conversion to Qref using the with this reference.

Name: 20220422_3202_phased_SNV_INDEL_SV 1kGP_high_coverage_Illumina.chr1.filtered.SNV_INDEL_SV_phased_panel.vcf.gz	
Source: http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20220422_3202_phased_SNV_INDEL_SV/

The reason the program would not create results with this reference was lack of ram without specifying the --maxChunkMemory argument to reflect the limited memory.

Phasing, imputation, and conversion to Qref was not possible with the following references.

Name: ALL.chr1.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz 20190312_biallelic_SNV_and_INDEL
Source: http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/release/20190312_biallelic_SNV_and_INDEL/

Name: ALL.chr1.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz
Source: http://hgdownload.cse.ucsc.edu/gbdb/hg19/1000Genomes/phase3/

The program indicates no matching variants. Maybe variant matching was not possible due to some formar or specification incompatibility. The reason for attempting to use more than one reference is to compare results and matching rates between the imputed vcf and the polygenic score variants with the aim to obtain the highest and most consistent rate possible across the polygenic calculations.

Matching rates of 88% were obtained with the server imputed vcf and 80% wirh the local install and reference using PGSC_Calc with various studies.

The imputed files where not compatible with a similar polygenic calculator called PRSK Calc, only the original vcf format which showed low matching rates but I don’t know the possible reasons. 

**This is how the original vcf looks like:**
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NG13RY1WVD
chr1    10611   rs189107123     C       G       260.77  PASS    AC=2;AF=1;AN=2;DB;DP=14;ExcessHet=3.0103;FS=0;MLEAC=2;MLEAF=1;QD=23.71;SOR=1.329;VQSLOD=-0.1914;culprit=DP      GT:AD:DP:GQ:PL      1/1:0,11:14:32:289,32,0
chr1    20316   rs1320311790    GA      G       108.73  PASS    AC=1;AF=0.5;AN=2;BaseQRankSum=-0.333;DB;DP=49;ExcessHet=3.0103;FS=0;MLEAC=1;MLEAF=0.5;MQRankSum=-2.098;NEGATIVE_TRAIN_SITE;QD=2.65;ReadPosRankSum=-2.272;SOR=0.941;VQSLOD=-3.673;culprit=QD GT:AD:DP:GQ:PL  0/1:34,7:41:99:146,0,1262
chr1    28563   rs4099234       A       G       146.84  PASS    AC=2;AF=1;AN=2;DB;DP=6;ExcessHet=3.0103;FS=0;MLEAC=2;MLEAF=1;QD=24.47;SOR=1.329;VQSLOD=-0.7649;culprit=DP       GT:AD:DP:GQ:PL      1/1:0,6:6:18:175,18,0
chr1    28590   rs757557694     T       TTGG    295.8   PASS    AC=1;AF=0.5;AN=2;BaseQRankSum=-1.593;DB;DP=9;ExcessHet=3.0103;FS=0;MLEAC=1;MLEAF=0.5;MQRankSum=1.59;NEGATIVE_TRAIN_SITE;QD=32.87;ReadPosRankSum=1.59;SOR=0.223;VQSLOD=-4.347;culprit=DP     GT:AD:DP:GQ:PL  0/1:1,8:9:18:333,0,18
chr1    28682   rs1490102872    G       A       152.03  PASS    AC=2;AF=1;AN=2;DB;DP=4;ExcessHet=3.0103;FS=0;MLEAC=2;MLEAF=1;QD=30.63;SOR=1.609;VQSLOD=0.0064;culprit=DP        GT:AD:DP:GQ:PGT:PID:PL:PS   1|1:0,4:4:12:1|1:28663_T_A:180,12,0:28663

**Here is a view of the server imputed vcf:**
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NG13RY1WVD
chr1    10177   rs367896724     A       AC      .       .       RefPanelAF=0.425319;AF=0.5;MAF=0.5;R2=1;AC=1;AN=2      GT:ADS:DS:GP     1|0:1,0:1:0,1,0
chr1    10235   rs540431307     T       TA      .       .       RefPanelAF=0.00119808;AF=0;MAF=0;R2=0;AC=0;AN=2 GT:ADS:DS:GP    0|0:0,0:0:1,0,0
chr1    10352   rs555500075     T       TA      .       .       RefPanelAF=0.4375;AF=0;MAF=0;R2=0;AC=0;AN=2     GT:ADS:DS:GP    0|0:0,0:0:1,0,0
chr1    10505   rs548419688     A       T       .       .       RefPanelAF=0.000199681;AF=0;MAF=0;R2=0;AC=0;AN=2       GT:ADS:DS:GP     0|0:0,0:0:1,0,0
chr1    10506   rs568405545     C       G       .       .       RefPanelAF=0.000199681;AF=0;MAF=0;R2=0;AC=0;AN=2       GT:ADS:DS:GP     0|0:0,0:0:1,0,0

Imputation output with **minimac4** created a report with PGSC-Calc with match rates at 80% but no polygenic scores. Some variation in the file format disables score calculations. I believe it could be lack of **dbSNP** codes in the ID field or lack of data in the info fields. I don’t know how to modify the file to replace ID’s with codes from a dbsnp file. Tried with:

bcftools annotate -a **/GRCh38_latest_dbSNP_all.vcf.gz** \ 
-c ID \ 
-Oz \ 
-o **/output-dbsnp/chr1.vcf.gz** 
**/input/chr1.vcf.gz** 

Here is a view of the minimac4 imputed output:
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NG13RY1WVD
chr1    10390   1:10390:CCCCTAACCC:C    CCCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCCTAA    C       .       .       AF=0;MAF=0;AVG_CS=1;R2=0;IMPUTED        HDS     0,0
chr1    10397   1:10399:C:A;1:10398:C:CCCCTAA;1:10397:CCCCTAA:C CCCCTAA ACCCTAA,CCCCTAACCCTAA,C .       .       AF=0,0,0;MAF=0;AVG_CS=1;R2=0;IMPUTED    HDS     0,0
chr1    10403   1:10403:A:ACCCTAACCC;1:10404:ACCCTAACCC:A       ACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC  ACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC,A   .       .       AF=0,0;MAF=0;AVG_CS=1;R2=0;IMPUTED     HDS      0,0
chr1    10415   1:10415:ACCCTAACCC:A    ACCCTAACCCTAACCCTAACCCTAAC      A       .       .       AF=0;MAF=0;AVG_CS=1;R2=0;IMPUTED        HDS     0,0
chr1    10420   1:10420:A:C     A       C       .       .       AF=0;MAF=0;AVG_CS=1;R2=0;IMPUTED        HDS     0,0
chr1    10421   1:10421:ACCCTAACCC:A    ACCCTAACCCTAACCCTAAC    A       .       .       AF=0;MAF=0;AVG_CS=1;R2=0;IMPUTEDHDS     0,0
chr1    10422   1:10422:CCCTAA:C        CCCTAA  C       .       .       AF=0;MAF=0;AVG_CS=1;R2=0;IMPUTED        HDS    0,0
chr1    10427   1:10427:ACCCT:A ACCCT   A       .       .       AF=0;MAF=0;AVG_CS=1;R2=0;IMPUTED        HDS     0,0
chr1    10428   1:10428:CCCTAA:C        CCCTAA  C       .       .       AF=0;MAF=0;AVG_CS=1;R2=0;IMPUTED        HDS    0,0
chr1    10430   1:10430:C:CT    C       CT      .       .       AF=0;MAF=0;AVG_CS=1;R2=0;IMPUTED        HDS     0,0
chr1    10433   1:10434:A:AC;1:10433:A:ACCCCTAAC;1:10435:ACCCTAAC:A     ACCCTAAC        ACCCCTAAC,ACCCCTAACCCCTAAC,A   ..       AF=0,0,0;MAF=0;AVG_CS=1;R2=0;IMPUTED    HDS     0,0

I tried to merge back biallelic sites in the input vcf that where multi-allelic and split using bcftools before imputation as suggested to compare results but it was not possible for many chromosome files to be completed due to the following error outputs causing an interrupted execution.

Command: bcftools norm -m+any
**Chr1:** The REF prefixes differ: C vs A (1,1)
Failed to merge alleles at chr1:1715541
**Chr2:** The REF prefixes differ: G vs C (1,1)
Failed to merge alleles at chr2:87355200
**Chr3:** The REF prefixes differ: G vs C (1,1)
Failed to merge alleles at chr3:195487256
**Chr4:** Lines   total/split/realigned/skipped:  5699894/0/0/0
**Chr5:** Lines   total/split/realigned/skipped:  5236194/0/0/0
**Chr6:** The REF prefixes differ: T vs A (1,1)
Failed to merge alleles at chr6:26670833
**Chr7:** The REF prefixes differ: T vs A (1,1)
Failed to merge alleles at chr7:62026380
**Chr8:** Lines   total/split/realigned/skipped:  4567802/0/0/0
**Chr9:** The REF prefixes differ: G vs C (1,1)
Failed to merge alleles at chr9:38779882
**Chr10:** The REF prefixes differ: A vs T (1,1)
Failed to merge alleles at chr10:17747004
**Chr11:** The REF prefixes differ: T vs A (1,1)
Failed to merge alleles at chr11:54926919
**Chr12:** Lines   total/split/realigned/skipped:  3846503/0/0/0
**Chr13:** Lines   total/split/realigned/skipped:  2841668/0/0/0
**Chr14:** The REF prefixes differ: T vs A (1,1)
Failed to merge alleles at chr14:19166620
**Chr15:** Lines   total/split/realigned/skipped:  2410965/0/0/0
**Chr16:** The REF prefixes differ: G vs C (1,1)
Failed to merge alleles at chr16:46384517
**Chr17:** Lines   total/split/realigned/skipped:  2314904/0/0/0
**Chr18:** Lines   total/split/realigned/skipped:  2254252/0/0/0
**Chr19:** The REF prefixes differ: G vs T (1,1)
Failed to merge alleles at chr19:20400650
**Chr20:** Lines   total/split/realigned/skipped:  1802905/0/0/0
**Chr21:** Lines   total/split/realigned/skipped:  1098579/0/0/0
**Chr22:** Lines   total/split/realigned/skipped:  1094839/0/0/0

The output for attempts to get stats for these files with bcftools stats produced error messages.

**Chr1:** [W::bcf_sr_add_reader] No BGZF EOF marker; file 'chr1.vcf.gz' may be truncated
[E::bcf_calc_ac] Incorrect AN/AC counts at chr1:1030496
**Chr2:** [W::bcf_sr_add_reader] No BGZF EOF marker; file 'chr2.vcf.gz' may be truncated
[E::bcf_calc_ac] Incorrect AN/AC counts at chr2:1155176
**Chr3:** [W::bcf_sr_add_reader] No BGZF EOF marker; file 'chr3.vcf.gz' may be truncated
[E::bcf_calc_ac] Incorrect AN/AC counts at chr3:3496304
**Chr4:** [E::bcf_calc_ac] Incorrect AN/AC counts at chr4:4218391
**Chr5:** [E::bcf_calc_ac] Incorrect AN/AC counts at chr5:793247
**Chr6:** [W::bcf_sr_add_reader] No BGZF EOF marker; file 'chr6.vcf.gz' may be truncated
[E::bcf_calc_ac] Incorrect AN/AC counts at chr6:9780183
**Chr7:** [W::bcf_sr_add_reader] No BGZF EOF marker; file 'chr7.vcf.gz' may be truncated
[E::bcf_calc_ac] Incorrect AN/AC counts at chr7:1673093
**Chr8:** [E::bcf_calc_ac] Incorrect AN/AC counts at chr8:4190543
**Chr9:** [W::bcf_sr_add_reader] No BGZF EOF marker; file 'chr9.vcf.gz' may be truncated
[E::bcf_calc_ac] Incorrect AN/AC counts at chr9:3291390
**Chr10:** [W::bcf_sr_add_reader] No BGZF EOF marker; file 'chr10.vcf.gz' may be truncated
[E::bcf_calc_ac] Incorrect AN/AC counts at chr10:2514810
**Chr11:** [W::bcf_sr_add_reader] No BGZF EOF marker; file 'chr11.vcf.gz' may be truncated
[E::bcf_calc_ac] Incorrect AN/AC counts at chr11:226757
**Chr12:** [E::bcf_calc_ac] Incorrect AN/AC counts at chr12:2396505
**Chr13:** [E::bcf_calc_ac] Incorrect AN/AC counts at chr13:23451913
**Chr14:** [W::bcf_sr_add_reader] No BGZF EOF marker; file 'chr14.vcf.gz' may be truncated
**Chr15:** [E::bcf_calc_ac] Incorrect AN/AC counts at chr15:22783437
**Chr16:** [W::bcf_sr_add_reader] No BGZF EOF marker; file 'chr16.vcf.gz' may be truncated
[E::bcf_calc_ac] Incorrect AN/AC counts at chr16:5697535
**Chr17:** [E::bcf_calc_ac] Incorrect AN/AC counts at chr17:1334432
**Chr18:** [E::bcf_calc_ac] Incorrect AN/AC counts at chr18:883056
**Chr19:** [W::bcf_sr_add_reader] No BGZF EOF marker; file 'chr19.vcf.gz' may be truncated
[E::bcf_calc_ac] Incorrect AN/AC counts at chr19:785122
**Chr20:** [E::bcf_calc_ac] Incorrect AN/AC counts at chr20:364763
**Chr21:** [E::bcf_calc_ac] Incorrect AN/AC counts at chr21:14327265
**Chr22:** [E::bcf_calc_ac] Incorrect AN/AC counts at chr22:17640898 

The Chr files with the output message **“[W::bcf_sr_add_reader] No BGZF EOF marker; file 'chr.vcf.gz' may be truncated”** are the same Chr files that produced the error messages from the bcftools -m+any command.

This did not occur with the imputation results generated by the local eagleimp installation nor with phasing done with eagleimp that was used to impute with minimac4. But as mentioned the imputed output from minimac did not generate scores.

The imputed outputs could not be used with a different calculator called PRS-Calc from https://prs.byu.edu/cli_download.html indicating unmerged multi-allelic positions.

Could you recommend solutions or point the reasons for these problems? Thank you.

**Comment by lwienbrandt** [comment]
I have to admit that I can hardly follow you. Anyway, I think I found several things you might take at look at.

1. EagleImp requires the filename of the reference file to start with the chromosome, e.g. 1.something or chr1.something. In the case of "ALL.chr1.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz" the software tries to find a chromosome named "ALL" in the file... Ok, I will put that on my list of things todo to make the software a bit more convenient. In your case, a rename which removes the "ALL." in the filename should do the job. 
However, for this file there is another problem which results from htslib I used internally to load vcf.gz files. The chromosome encoding in the ALL.chr1....vcf.gz is "1" while the encoding in your input file is probably "chr1" which is not considered equal by htslib. That's probably also a reason why no common variants are found, if you use the reference directly as vcf.gz.
Here, I recommend to convert the reference to a Qref file first because the internal chromosome encoding doesn't matter anymore and can be either "1" or "chr1" then. It is also faster, if you need the reference to be used more often, as directly reading a vcf.gz reference takes ages.
So, I renamed and converted this reference to Qref and tried to impute an example dataset in hg38 on my computer and it worked without a problem.
For "1kGP_high_coverage_Illumina.chr1.filtered.SNV_INDEL_SV_phased_panel.vcf.gz", I only renamed the file to "chr1.1kGP_high_coverage_Illumina..." and used it directly to impute my example dataset. This also worked without a problem. NOTE: For this example it would accidentally also work without renaming as "1kGP" would be identified as chromosome 1...

2. Multi-allelic variants are always a problem. It is indeed not possible to phase a multi-allic marker in your target set, so multi-allelic variants in the target are always excluded. From the reference though, you can exclude them via --excludeMultiAllRef. However, both of your mentioned references don't contain multi-allelic variants.
Of course, you can split multi-allelics in your target before you impute it, but keep in mind, that the imputation output only holds variants, that are also included in the reference. Target-only variants are skipped anyway. So, the only chance you have in phasing a multi-allelic variant is, when the splitted version is also included as a splitted variant in the reference AND it must have been splitted in the same way, that is the reference allele should be the same in both versions after splitting. For example, if you have a variant A C,G splitted to A C and A G, the software won't find a match, if the reference was encoded as C A,G and splitted to C A (match if --allowRefAltSwap is set) and C G (definitely no match). Probably, this is the reason for your errors you get when trying to merge back multi-allelics?
Also, keep in mind, that the allele encoding is also the same as in the reference, i.e. if you have a variant A G in your target, but the reference is G A at that position, the software only matches the variant if --allowRefAltSwap is set, and the output will be G A.

4. I haven't understood which files cause the "No BGZF EOF marker" warning together with the "Incorrect AN/AC counts" error. Is it EagleImp output or minimac4 output? Or is this after trying to merge multi-allelics with bcftools? If it's EagleImp, please consider my above mentioned recommendations first and try again. If the error still remains, I really need further infos on your input before I can trace that error.
Note, that I didn't encounter errors or warnings when I ran bcftools stats on my imputed files with your mentioned references.

Best, Lars
